name: Python CI

on:
  push:
    branches: [main]  # Trigger on push to main
  pull_request:
    branches: [main]  # Trigger on PR to main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repo's code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Change this to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -e .  # Install your project in editable mode

      - name: Run tests with coverage
        run: |
          PYTHONPATH=src pytest --cov=newtonmethod --cov-report=xml  # Run pytest with coverage
